apiVersion: apps/v1
kind: Deployment
metadata:
  name:  minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft-server
  template:
    metadata:
      labels:
        app: minecraft-server
    spec:
      restartPolicy: Always
      volumes:
          - name: minecraft-data
            persistentVolumeClaim:
              claimName: minecraft-data-pvc 
      containers:
      - image:  mnehalb/nt-minecraft:copy
        name:  minecraft-container
        imagePullPolicy: Always  
        resources:
          requests:
            cpu: "2"
            memory: "2Gi"
          limits:
            memory: 4Gi         
        ports:
        - containerPort:  25565
          name:  mc-port
        volumeMounts:
          - name: minecraft-data
            mountPath:  /data 
---
kind: Service
apiVersion: v1
metadata:
  name: minecraft-service
spec:
  selector:
    app:  minecraft-server
  type:  LoadBalancer 
  ports:
  - name:  mc-port
    port:  80
    targetPort:  25565