apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name:  minecraft
  labels:
    app: minecraft-server
spec:
  template:
    metadata:
      labels:
        name:  minecraft-server
    spec:
      containers:
      - image:  mnehalb/nt-minecraft
        name:  minecraft-container
        resources:
          requests:
            cpu: "20m"
            memory: "55M"
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 30
          timeoutSeconds: 10
        env:
        - name:  ENVVARNAME
          value:  ENVVARVALUE       
        ports:
        - containerPort:  5000
          name:  my-name
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
        - name: data
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always