---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-data
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  mountOptions:
   - hard
   - nfsvers=4.1
  nfs:
    path: '/mnt/nfs/minecraft-server/'
    server: 192.168.10.37
