apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name:  minecraft
  labels:
    app: minecraft-server
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name:  minecraft-server
    spec:
      containers:
      - image:  mnehalb/nt-minecraft
        name:  minecraft-container
        resources:
          requests:
            cpu: "2"
            memory: "4G"       
        ports:
        - containerPort:  25565
          name:  mc-port
        volumeMounts:
        - mountPath: /app
          name: mc-volume
      volumes:
        - name: mc-volume
          emptyDir: {}
      restartPolicy: Always
      imagePullPolicy: Always