
[general]

	#Spawn settings
	[general.spawnrate]
		#
		#Biome name where Brown Scorpion should spawn
		biome_name_1 = "minecraft:desert,minecraft:badlands,minecraft:eroded_badlands"
		#
		#Biome name where Emperor Scorpion should spawn
		biome_name_2 = "minecraft:desert,minecraft:badlands,minecraft:eroded_badlands"
		#
		#Biome name where Nether Scorpion should spawn
		biome_name_3 = "minecraft:soul_sand_valley"

		#Brown Scorpion
		[general.spawnrate.brown_scorpion]
			#Spawn Chance
			#Range: > 0
			weight = 5
			#Monster Spawn Minimum Number
			#Range: > 0
			min = 0
			#Monster Spawn Maximum Number
			#Range: > 0
			max = 1
			#Poison duration
			#Range: > 0
			duration = 20
			#Health points
			#Range: > 1
			hp = 30
			#Damage
			#Range: > 1
			damage = 4

		#Emperor Scorpion
		[general.spawnrate.emperor_scorpion]
			#Spawn Chance
			#Range: > 0
			weight = 5
			#Monster Spawn Minimum Number
			#Range: > 0
			min = 0
			#Monster Spawn Maximum Number
			#Range: > 0
			max = 1
			#Poison duration
			#Range: > 0
			duration = 5
			#Health points
			#Range: > 1
			hp = 35
			#Damage
			#Range: > 1
			damage = 6

		#Nether Scorpion
		[general.spawnrate.nether_scorpion]
			#Spawn Chance
			#Range: > 0
			weight = 5
			#Monster Spawn Minimum Number
			#Range: > 0
			min = 0
			#Monster Spawn Maximum Number
			#Range: > 0
			max = 1
			#Poison duration
			#Range: > 0
			duration = 8
			#Health points
			#Range: > 1
			hp = 50
			#Damage
			#Range: > 1
			damage = 7

