
["Config for the Stardew Armory mod"]
	#Should an indicator appear above the crosshair when the player is holding a tool with iridium mode on. Default value is true
	"Iridium bool" = true
	#Should Guild structures spawn in the world. Default value is true
	"Guild bool" = true
	#If the Guild structure is enabled, what is the minimum amount of chunks apart each should be. Default value is 38
	"Minimum int" = 38
	#If the Guild structure is enabled, what is the average amount of chunks apart each should be. Default value is 50
	"Average int" = 50
	#How many veins of iridium ore should spawn per chunk. Default value is 6
	"Iridium int" = 6
	#How many veins of cinder ore should spawn per chunk. Default value is 20
	"Cinder int" = 20
	#Chance for a zombie to spawn with a wooden club in hand. Accepts values within a range of [1,0). Default value is 0.05 (5%)
	"Club double" = 0.05
	#Should Lucky Hit play the critical sound effect. Default value is true
	"Crit bool" = true
	#How likely the warrior ring is to proc after a kill (1/# chance). Default value is 8
	"Warrior int" = 8

