#Amount of inventory rows a leather bag of holding has.
#Range: 1 ~ 9
leather_bag_rows = 1
#Amount of inventory rows an iron bag of holding has.
#Range: 1 ~ 9
iron_bag_rows = 3
#Chance that one level of preservation will be lost on a bag of holding when dying.
#Range: 0.0 ~ 1.0
preservation_level_loss_chance = 1.0
#Items that should not be allowed to be put into a bag, mainly intended to prevent nesting with backpacks from other mods.
#Shulker boxes and other bags of holding are disabled by default.
#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
bag_of_holding_blacklist = []
#Amount of inventory rows a golden bag of holding has.
#Range: 1 ~ 9
golden_bag_rows = 6

